version: '3.8'
services:
  chic-bio-link:
    build: .
    image: joaovnsouza/chic-bio-link:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chic-bio-link.rule=Host(`joaosouza.site`)"
      - "traefik.http.routers.chic-bio-link.entrypoints=websecure"
      - "traefik.http.routers.chic-bio-link.tls=true"
      - "traefik.http.services.chic-bio-link.loadbalancer.server.port=80"
    restart: unless-stopped
